Develop
ablehope/mesto-backend pull request #1
Opened 2019-11-04 15:35 UTC by ablehope

2019-11-04 22:19 UTC, koras requested changes
Надо поправить получение пользователя

2019-11-04 22:19 UTC, koras commented on routes/users.js
> +  res.status(200).send(`Пользователь: ${result}`);
Пользователь: [object Object]
Здесь должен быть json

2019-11-04 22:19 UTC, koras commented on routes/users.js
> +  res.status(200).send(`Пользователь: ${result}`);
Это критическая ошибка

2019-11-04 22:19 UTC, koras commented on app.js
> +const path = require('path');
всё корректно

2019-11-04 22:19 UTC, koras commented on README.md
> +
крутое описание

2019-11-05 08:02 UTC, p-aliaksandr commented on routes/users.js
> +  res.status(200).send(`Пользователь: ${result}`);
> Это критическая ошибка

поправил, теперь данные о пользователе отображаются корректно.

2019-11-05 08:04 UTC, ablehope commented on README.md
> +
> крутое описание

спасибо:)

2019-11-05 17:22 UTC, koras approved these changes
Поправили, принимается

2019-11-05 17:31 UTC, merged